---
title: AA Hodge on the Mode of Baptism
tags: religion

date: '2019-12-10'
---

> The Confession teaches that the command to baptize is a command to wash with water in the name of the Trinity. It is often, but erroneously, supposed that the controversy between our Baptist bretheren and _the rest of the Christian Church_ with respect to Baptism is a question of mode; they affirming that the only right to mode is to immerse -- we affirming that the best mode is to sprinkle. This is a great mistake. The real Baptist position -- as stated by Dr. Alexander Carson -- is, that the command to baptize is a simple and single command to immerse, in order to symbolize the death, burial, and ressurection of othe believer with Christ. The _true_ position maintained by other Christians is, that Baptism is a simple and single command to wash with water, in order to symbolize the purification wrought by the Holy Ghost. Hence the mode of washing has nothing to do with it. It is necessarily perfectly indifferent, so that it be decent. According to our view, the essential matter is the water, and the application of the water in the name of the Trinity. According to their view, the essential matter is the burial, total immersion, in water or sand, as the case may be. The evidence of the truth of the view entertained by the vast majority of Christ's Church is as follows: --
>
> **1.** The word baptizo in its classical usage means to dip, to moisten, to wet, to purify, to wash.
>
> **2.** In the Septuagint, baptizo (and another variant of the same root) occurs five times. Thus, Daniel 4:33, Nebuchadnezzar is said to have been wet (baptized) with the dew of heaven. Numbers 19:21 also expects the washing required in ritual purification will be done via sprinkling.
>
> **3.** In the New Testament, the greek for "to baptize" is used interchangably with a word which means only "to wash". Compare Mark 7: 3,4; Luke 11:38; Matthew 15: 2, 20: and observe -- (a.) That to baptize is there used interchangeably with to wash. (b.) The washing was to effect purification, for the unbaptiazed hands are called the unwashed and unclean hands. (c.) The common mode of washing hands in those countries is to pour water on them. The rich have servants to pour the water on their hands; the poor pour the water on their own hands.
>
> **4.** When John's disciples dispubted about baptism, it is expressly said to ahve been a dispute about _purification_. (John 3:25, 4:2)
>
> **5.** The same idea is uniformly expressed by the word _baptism_, or _baptisms_, in the New Testament. In Mark 7:2-8 we read of the baptisms of cups, pots, brazen vessels, and tables (couches upon which several persons reclined at table). These things could not be, and were not, immersed. The whole object of the service was not burial, but \__purification_. In Hebrews 9:10, Paul says that the first tabernacle "stood only in meats and drinks, and divers baptisms;" and below, in verses 13, 19, 21, he specifies some of these divers baptisms -- "For if the blood of bulls and of goats, and the ashes of an heifer sprinking the unclean, sanctifies to the purifying of the flesh;" and "Moses sprinkled both the book and all the people, and the tabernacle and all the vessels of the ministry."
>
> **6.** Baptism with water is emblematical of baptism by the Holy Ghost, the object of which is spiritual purification. (Matthew 3:11; Mark 1:8; Luke 3:16; John 1:26, 33; Acts 1:5 11:16) Spiritual baptism is called "the washing of regeneration and renewing of the Holy Ghost." (Titus 3:5) Baptism with water symbolizes baptism by the Holy Ghost. Buty baptism by the HolyGhost unites us to Christ, and makes us one with him in his death, in his ressurrection, in his new life unto God, his righteousness, his inheritance, etc., etc. Spiritual baptism carries all these consequences, and water baptism represents spiritual baptism; _therefore_ we are said to be baptized into Christ, into his death, into one body -- to be buried with him, to rise with him, so as to walk with him in newness of life -- to put on Christ (as a garment), to be planted together with him (as a tree), etc. None of these have anything to do with the mode of baptism, because it is simply absurd to suppose that tthe same action can at the same time symbolize things so different as burial, putting on clothes, and planting trees. The real order is: washing with water represents washing of the Spirit; washing of the Spirit unites to Christ; union with Christ involves all the consequences above mentioned.
>
> **7.** Baptism of the Holy Ghost, of which water baptism i sthe emblem, is never set forth in Scripture as an "immersion", but always as a "_pouring_" and "_sprinkling_". (Acts 2:1-4, 32, 33, 10:44-48, 11:15,16) Of the gift of the Holy Ghost it is said, he "came down from heaven", was "poured out", "shed forth", "fell on them." Isaiah 44:3 - "I will pour my Spirit upon thy seed". Isaiah 52:15 - "So shall he sprinkle many nations". Ezekiel 36:25-27 - "Then will I sprinkle clean water upon you, and ye shall be clean," etc. Joel 2: 28,28 - "I will pour out my Spirit upon all flesh."
>
> **8.** The universally prevalent manner of effecting the rite of purification among the Jews -- from the analogy of which Christian Baptism was taken -- was by sprinkling, and _not_ by immersion. The hands and feet of the priests were to be washed at the brazen laver, from which water poured out through spouts or cocks. Exodus 30:18-21; 2 Chronicles 4:6, 1 Kings 7:27-39. See also Leviticus 8:30; 14:7, 51; Exodus 24:5-8; Numbers 8: 6-7; Hebrews 9: 12-22.
>
> **9.** In 1 Corinthians 10: 1, 2 the Israelites are said to have been "baptized unto Moses in the cloud and in the sea." Compare Exodus 14: 19-31. But the Egyptions who were immersed were _not_ baptized; and the Israelites who were baptized were _not_ immersed. In 1 Peter 3:20, 21 it is said that Baptism is the anti-type of the salavation of the eight souls in the ark. Yet the very gist of their salvation consisted in their _not_ being immersed.
>
> **10.** Among all the recorded instances of Baptism performed by John the Baptist and the apostles, there is not one in which immersion is asserted, while there are many in which it was highly improbably -- (a.) Because the apostles baptizing and the early converts baptized were all JEws, accustomed to purify by pouring and sprinkilng. (b.) Because of the vast multitudes baptized at one time, and the known scarcity of water in Jerusalem and generally in the situations spoken of. The eunuch was baptized on the roadside in a desert country. (Acts 8: 26-30) Three thousand were baptized in one day in the dry city of Jerusalem, which depends upon rain-water stored in tanks and cisterns. (Acts 2: 37-41) _Vast multitudes_ swarmed to John (Matthew 3: 5,6) The jailer was baptized in prison at midnight (Acts 16: 25-33) Paul was baptized by Ananias right at his bedisde. Ananias said "_Standing up, be baptized_"; and "_standing up he was baptized._" (Acts 9:18; 22:16) (c.) The earliest pictorial representations of baptism, dating from the second or third century, all indicate that the manner of applying water to the body of the baptized was by pouring. (d.) It is done in the same way universaslly by Eastern Christians at the present time.

**Hodge, Archibald Alexander. Westminer Confession, A Commentary. Banner of Truth Trust, 2013, pp 340-343**
